### PR TITLE
Embed Tag Creator

### PR DESCRIPTION
**Pull request by romancow**
This embeds the "schema form" into the "Append Artifact Dialog", instead of forcing one to go to a separate page and upload a tags file. The dialog is now 2-steps -- a tag form, followed by setting the name and selecting upload files.

It also replaces the display in an artifact's "view metadata" dialog with a readonly version of the schema form.

Screen Shot 2024-06-14 at 12 44 10 PM

Screen Shot 2024-06-14 at 12 44 26 PM

Screen Shot 2024-06-14 at 12 44 45 PM

### CODE REVIEW

**Review by pmeijer — CHANGES_REQUESTED** [review]
Code looks good to me and all in all good feature - thanks! For the UI I have some feedback and requests..
1. Can you use the same tag dialog for when creating a repository?
2. Can you make the tag dialog bigger? Almost full-screen.
3. Editing the existing tags needs to request the tags and repopulated the modal. Currently it looks like the state is coming from the modal itself (for uploading you could consider keeping it this way as it's likely you want to be able prepopulate - but if you do make sure to add a clear button to reset it).

**Comment by romancow** [comment]
@pmeijer

1. Yes, forgot about that. Didn't realize it was using a different one. 🤦 
2. I'll look into it.
3. Yeah, I think I forgot a step here altogether. Looks like it isn't even setting the `tags` value i.nside the `AppendArtifactDialog`. 🤦

**Comment by romancow** [comment]
Ok @pmeijer, I think I've addressed your issues. Please take another look when you get a chance.

Also, fixed some style related issues and added a button to clear all tags.

Screen Shot 2024-07-02 at 8 44 01 PM

**Review by pmeijer — APPROVED** [review]
Looks good - all my requests have been resolved :+1:

**Pull request merged**
